"""empty message

Revision ID: 36b28a3fe64d
Revises: 
Create Date: 2025-04-03 01:10:38.058335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b28a3fe64d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=50), nullable=True),
    sa.Column('enterprise_size', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_enterprise_size'), 'users', ['enterprise_size'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_income'), 'users', ['income'], unique=False)
    op.create_index(op.f('ix_users_job'), 'users', ['job'], unique=False)
    op.create_index(op.f('ix_users_location'), 'users', ['location'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_location'), table_name='users')
    op.drop_index(op.f('ix_users_job'), table_name='users')
    op.drop_index(op.f('ix_users_income'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_enterprise_size'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
