"""empty message

Revision ID: 7d2352dfad5d
Revises: 1cc100581598
Create Date: 2025-04-03 20:53:29.456836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2352dfad5d'
down_revision: Union[str, None] = '1cc100581598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('studentid', sa.String(length=50), nullable=True))
    op.drop_index('ix_students_student_id', table_name='students')
    op.create_index(op.f('ix_students_studentid'), 'students', ['studentid'], unique=False)
    op.drop_column('students', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_id', sa.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_students_studentid'), table_name='students')
    op.create_index('ix_students_student_id', 'students', ['student_id'], unique=False)
    op.drop_column('students', 'studentid')
    # ### end Alembic commands ###
