"""empty message

Revision ID: 8f5436362390
Revises: 8017278a7926
Create Date: 2025-04-03 22:11:12.255927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8f5436362390'
down_revision: Union[str, None] = '8017278a7926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scholarships') as batch_op:
        batch_op.alter_column('raw_text',
                   existing_type=sa.JSON(),
                   type_=sa.String(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scholarships') as batch_op:
        batch_op.alter_column('raw_text',
                   existing_type=sa.JSON(),
                   type_=sa.String(),
                   existing_nullable=True)
    # ### end Alembic commands ###
