"""empty message

Revision ID: dcdcc4368836
Revises: e03bdec381b7
Create Date: 2025-04-04 02:26:39.628703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdcc4368836'
down_revision: Union[str, None] = 'e03bdec381b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_enterprise_size', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_income', table_name='users')
    op.drop_index('ix_users_job', table_name='users')
    op.drop_index('ix_users_location', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('income', sa.INTEGER(), nullable=True),
    sa.Column('job', sa.VARCHAR(length=50), nullable=True),
    sa.Column('enterprise_size', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_location', 'users', ['location'], unique=False)
    op.create_index('ix_users_job', 'users', ['job'], unique=False)
    op.create_index('ix_users_income', 'users', ['income'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_enterprise_size', 'users', ['enterprise_size'], unique=False)
    # ### end Alembic commands ###
